language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
addons:
  firefox: 46.0.1
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
- PLONE_VERSION=5.2
matrix:
  fast_finish: true
install:
- sed -ie "s#test-5.1#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- export ROBOT_SELENIUM2LIBRARY_RUN_ON_FAILURE="Capture Page Screenshot"
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/test
after_script:
- pip install coverage
- coverage run bin/test
# Coveralls
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
